# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'QuickWallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickWallet

  target 'QuickWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'QuickWallet-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickWallet-tvOS

  target 'QuickWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
