# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'QuickWallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickWallet

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'react-native-haptic-feedback', :path => '../node_modules/react-native-haptic-feedback'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'QuickWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'QuickWallet-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickWallet-tvOS

  target 'QuickWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
